# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest


stages:
  - build
  - deploy

variables:
    DOCKER_HOST: tcp://localhost:2375
    
services:
  - docker:dind

build-master:
  stage: build
  script:
    - env
#    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#    - docker build --pull -t "$CI_REGISTRY_IMAGE:master" ./php
#    - docker push "$CI_REGISTRY_IMAGE:master"
  only:
    - master

    
deployment:
  image: lachlanevenson/k8s-kubectl:v1.13.6
  environment:
    name: DEV
    url: https://master.116.203.190.175.xip.io
  stage: deploy
  script:
    - kubectl version
    - kubectl create secret -n "${KUBE_NAMESPACE}" docker-registry gitlab-registry --docker-server="${CI_REGISTRY}" --docker-username="${CI_REGISTRY_USER}" --docker-password="${CI_JOB_TOKEN}" --docker-email="${GITLAB_USER_EMAIL}" -o yaml --dry-run | sed 's/dockercfg/dockerconfigjson/g' | kubectl replace -n "$KUBE_NAMESPACE" --force -f -
    - sed -i "s/__KUBE_NAMESPACE__/${KUBE_NAMESPACE}/" deployment.yaml
    - sed -i "s/__CI_BUILD_REF_SLUG__/${CI_BUILD_REF_SLUG}/" deployment.yaml
    - sed -i "s/__VERSION__/${CI_COMMIT_REF_NAME}/" deployment.yaml
    - kubectl apply -f deployment.yaml
